[[module.imports]]
# Example: use the PaperMod theme (replace with desired theme)
path = "github.com/adityatelange/hugo-PaperMod"
# If you want to keep multiple themes available, add additional blocks:
# [[module.imports]]
# path = "github.com/reorx/hugo-PaperModX"
